.TH "inc/colors.h" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/colors.h \- 
.PP
Video Color defines.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBLACK\fP   0x0"
.br
.ti -1c
.RI "#define \fBBLUE\fP   0x1"
.br
.ti -1c
.RI "#define \fBGREEN\fP   0x2"
.br
.ti -1c
.RI "#define \fBCYAN\fP   0x3"
.br
.ti -1c
.RI "#define \fBRED\fP   0x4"
.br
.ti -1c
.RI "#define \fBMAGENTA\fP   0x5"
.br
.ti -1c
.RI "#define \fBBROWN\fP   0x6"
.br
.ti -1c
.RI "#define \fBLIGHT_GREY\fP   0x7"
.br
.ti -1c
.RI "#define \fBDARK_GREY\fP   0x8"
.br
.ti -1c
.RI "#define \fBLIGHT_BLUE\fP   0x9"
.br
.ti -1c
.RI "#define \fBLIGHT_GREEN\fP   0xA"
.br
.ti -1c
.RI "#define \fBLIGHT_CYAN\fP   0xB"
.br
.ti -1c
.RI "#define \fBLIGHT_RED\fP   0xC"
.br
.ti -1c
.RI "#define \fBLIGHT_MAGENTA\fP   0xD"
.br
.ti -1c
.RI "#define \fBLIGHT_BROWN\fP   0xE"
.br
.ti -1c
.RI "#define \fBWHITE\fP   0xF"
.br
.ti -1c
.RI "#define \fBsetColor\fP(bkg, text)   (((bkg) << 4) + (text))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Video Color defines. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBcolors.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define BLACK   0x0"
.PP
Definition at line 13 of file colors.h.
.SS "#define BLUE   0x1"
.PP
Definition at line 14 of file colors.h.
.SS "#define BROWN   0x6"
.PP
Definition at line 19 of file colors.h.
.SS "#define CYAN   0x3"
.PP
Definition at line 16 of file colors.h.
.SS "#define DARK_GREY   0x8"
.PP
Definition at line 21 of file colors.h.
.SS "#define GREEN   0x2"
.PP
Definition at line 15 of file colors.h.
.SS "#define LIGHT_BLUE   0x9"
.PP
Definition at line 22 of file colors.h.
.SS "#define LIGHT_BROWN   0xE"
.PP
Definition at line 27 of file colors.h.
.SS "#define LIGHT_CYAN   0xB"
.PP
Definition at line 24 of file colors.h.
.SS "#define LIGHT_GREEN   0xA"
.PP
Definition at line 23 of file colors.h.
.SS "#define LIGHT_GREY   0x7"
.PP
Definition at line 20 of file colors.h.
.SS "#define LIGHT_MAGENTA   0xD"
.PP
Definition at line 26 of file colors.h.
.SS "#define LIGHT_RED   0xC"
.PP
Definition at line 25 of file colors.h.
.SS "#define MAGENTA   0x5"
.PP
Definition at line 18 of file colors.h.
.SS "#define RED   0x4"
.PP
Definition at line 17 of file colors.h.
.SS "#define setColor(bkg, text)   (((bkg) << 4) + (text))"
.PP
Definition at line 30 of file colors.h.
.SS "#define WHITE   0xF"
.PP
Definition at line 28 of file colors.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
