.TH "directory_t" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
directory_t \- 
.PP
The page directory typedef.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SH "Detailed Description"
.PP 
The page directory typedef. 

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
