.TH "frame" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frame \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBassigned\fP"
.br
.ti -1c
.RI "unsigned int \fBaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file types.h.
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBaddress\fP"
.PP
Definition at line 99 of file types.h.
.SS "int \fBassigned\fP"
.PP
Definition at line 98 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
