.TH "inc/kasm.h" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/kasm.h \- 
.PP
Kernel utilities.  

.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fB_read_msw\fP ()"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "void \fB_lidt\fP (\fBIDTR\fP *\fBidtr\fP)"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "void \fB_mascaraPIC1\fP (byte mascara)"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "void \fB_mascaraPIC2\fP (byte mascara)"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "void \fB_Cli\fP (void)"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "void \fB_Sti\fP (void)"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "void \fB_debug\fP (void)"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "unsigned \fBgetCodeSegment\fP ()"
.br
.RI "\fIBrief. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Kernel utilities. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBkasm.h\fP.
.SH "Function Documentation"
.PP 
.SS "void _Cli (void)"
.PP
Brief. Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SS "void _debug (void)"
.PP
Brief. Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SS "void _lidt (\fBIDTR\fP * idtr)"
.PP
Brief. \fBParameters:\fP
.RS 4
\fIidtr\fP ParamBrief.
.RE
.PP
Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SS "void _mascaraPIC1 (byte mascara)"
.PP
Brief. \fBParameters:\fP
.RS 4
\fImascara\fP ParamBrief.
.RE
.PP
Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SS "void _mascaraPIC2 (byte mascara)"
.PP
Brief. \fBParameters:\fP
.RS 4
\fImascara\fP ParamBrief.
.RE
.PP
Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SS "unsigned int _read_msw ()"
.PP
Brief. Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SS "void _Sti (void)"
.PP
Brief. Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SS "unsigned getCodeSegment ()"
.PP
Brief. Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
