.TH "src/kernelDepth.c" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/kernelDepth.c \- 
.PP
Kernel syscalls depth utilities implementation.  

.SH SYNOPSIS
.br
.PP
\fC#include '../inc/kernelDepth.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBincreaseKernelDepth\fP (void)"
.br
.RI "\fIThis function increases the depth relating to the iteration of system calls maintaining the presence of the kernel heap pages. \fP"
.ti -1c
.RI "void \fBdecreaseKernelDepth\fP (void)"
.br
.RI "\fIThis function decreases the depth relating to the iteration of system calls maintaining the presence of the kernel heap pages if needed. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Kernel syscalls depth utilities implementation. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBkernelDepth.c\fP.
.SH "Function Documentation"
.PP 
.SS "void decreaseKernelDepth (void)"
.PP
This function decreases the depth relating to the iteration of system calls maintaining the presence of the kernel heap pages if needed. \fBSee also:\fP
.RS 4
\fBdecreaseKernelDepth()\fP 
.RE
.PP

.PP
Definition at line 23 of file kernelDepth.c.
.SS "void increaseKernelDepth (void)"
.PP
This function increases the depth relating to the iteration of system calls maintaining the presence of the kernel heap pages. \fBSee also:\fP
.RS 4
\fBdecreaseKernelDepth()\fP 
.RE
.PP

.PP
Definition at line 14 of file kernelDepth.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
