.TH "inc/kernel.h" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/kernel.h \- 
.PP
Kernel header file.  

.SH SYNOPSIS
.br
.PP
\fC#include 'kasm.h'\fP
.br
\fC#include 'kc.h'\fP
.br
\fC#include 'system.h'\fP
.br
\fC#include 'int_handlers.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include 'stdio.h'\fP
.br
\fC#include 'string.h'\fP
.br
\fC#include 'video_driver.h'\fP
.br
\fC#include 'memModule.h'\fP
.br
\fC#include 'ttys.h'\fP
.br
\fC#include 'kMalloc.h'\fP
.br
\fC#include 'sysProcess.h'\fP
.br
\fC#include 'bin.h'\fP
.br
\fC#include 'shMemory.h'\fP
.br
\fC#include 'semaphore.h'\fP
.br

.SH "Detailed Description"
.PP 
Kernel header file. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBkernel.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
