.TH "page" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBpresent\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBwriteable\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBuser\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBdirectWrite\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBdisableCache\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBaccessed\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBdirty\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBreserved\fP: 5"
.br
.ti -1c
.RI "unsigned int \fBaddress\fP: 20"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file types.h.
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBaccessed\fP"
.PP
Definition at line 72 of file types.h.
.SS "unsigned int \fBaddress\fP"
.PP
Definition at line 75 of file types.h.
.SS "unsigned int \fBdirectWrite\fP"
.PP
Definition at line 70 of file types.h.
.SS "unsigned int \fBdirty\fP"
.PP
Definition at line 73 of file types.h.
.SS "unsigned int \fBdisableCache\fP"
.PP
Definition at line 71 of file types.h.
.SS "unsigned int \fBpresent\fP"
.PP
Definition at line 67 of file types.h.
.SS "unsigned int \fBreserved\fP"
.PP
Definition at line 74 of file types.h.
.SS "unsigned int \fBuser\fP"
.PP
Definition at line 69 of file types.h.
.SS "unsigned int \fBwriteable\fP"
.PP
Definition at line 68 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
