.TH "pQueueCDT" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pQueueCDT \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlistWithPrio\fP * \fBqueue\fP"
.br
.ti -1c
.RI "void *(* \fBcpyFn\fP )(void *)"
.br
.ti -1c
.RI "void(* \fBfreeFn\fP )(void *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file pQueueP.c.
.SH "Field Documentation"
.PP 
.SS "void*(* \fBcpyFn\fP)(void *)"
.PP
Definition at line 33 of file pQueueP.c.
.SS "void(* \fBfreeFn\fP)(void *)"
.PP
Definition at line 34 of file pQueueP.c.
.SS "\fBlistWithPrio\fP* \fBqueue\fP"
.PP
Definition at line 32 of file pQueueP.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
