.TH "registers" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
registers \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBedi\fP"
.br
.ti -1c
.RI "unsigned \fBesi\fP"
.br
.ti -1c
.RI "unsigned \fBebp\fP"
.br
.ti -1c
.RI "unsigned \fBesp\fP"
.br
.ti -1c
.RI "unsigned \fBebx\fP"
.br
.ti -1c
.RI "unsigned \fBedx\fP"
.br
.ti -1c
.RI "unsigned \fBecx\fP"
.br
.ti -1c
.RI "unsigned \fBeax\fP"
.br
.ti -1c
.RI "unsigned \fBerror\fP"
.br
.ti -1c
.RI "unsigned \fBeip\fP"
.br
.ti -1c
.RI "unsigned \fBcs\fP"
.br
.ti -1c
.RI "unsigned \fBeflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file exceptions.c.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBcs\fP"
.PP
Definition at line 87 of file exceptions.c.
.SS "unsigned \fBeax\fP"
.PP
Definition at line 84 of file exceptions.c.
.SS "unsigned \fBebp\fP"
.PP
Definition at line 79 of file exceptions.c.
.SS "unsigned \fBebx\fP"
.PP
Definition at line 81 of file exceptions.c.
.SS "unsigned \fBecx\fP"
.PP
Definition at line 83 of file exceptions.c.
.SS "unsigned \fBedi\fP"
.PP
Definition at line 77 of file exceptions.c.
.SS "unsigned \fBedx\fP"
.PP
Definition at line 82 of file exceptions.c.
.SS "unsigned \fBeflags\fP"
.PP
Definition at line 88 of file exceptions.c.
.SS "unsigned \fBeip\fP"
.PP
Definition at line 86 of file exceptions.c.
.SS "unsigned \fBerror\fP"
.PP
Definition at line 85 of file exceptions.c.
.SS "unsigned \fBesi\fP"
.PP
Definition at line 78 of file exceptions.c.
.SS "unsigned \fBesp\fP"
.PP
Definition at line 80 of file exceptions.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
