.TH "S_TABLE" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S_TABLE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bttlship.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsemid\fP"
.br
.ti -1c
.RI "int \fBwaitSemid\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBpid_t\fP \fBpid\fP"
.br
.ti -1c
.RI "   int \fBbsites\fP"
.br
.ti -1c
.RI "} \fBplayer\fP [2]"
.br
.ti -1c
.RI "char \fBsea\fP [N_X][N_Y]"
.br
.ti -1c
.RI "char \fBflg\fP [N_X][N_Y]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file bttlship.h.
.SH "Field Documentation"
.PP 
.SS "int \fBbsites\fP"
.PP
Definition at line 55 of file bttlship.h.
.SS "char \fBflg\fP[N_X][N_Y]"
.PP
Definition at line 58 of file bttlship.h.
.SS "\fBpid_t\fP \fBpid\fP"
.PP
Definition at line 54 of file bttlship.h.
.SS "struct { ... }         \fBplayer\fP[2]"
.SS "char \fBsea\fP[N_X][N_Y]"
.PP
Definition at line 57 of file bttlship.h.
.SS "int \fBsemid\fP"
.PP
Definition at line 51 of file bttlship.h.
.SS "int \fBwaitSemid\fP"
.PP
Definition at line 52 of file bttlship.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
