.TH "semaphore" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
semaphore \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBkey_t\fP \fBsemid\fP"
.br
.ti -1c
.RI "int \fBsemval\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBsempid\fP"
.br
.ti -1c
.RI "\fBsemQueue_t\fP * \fBwaitQueue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file semaphore.c.
.SH "Field Documentation"
.PP 
.SS "\fBkey_t\fP \fBsemid\fP"
.PP
Definition at line 18 of file semaphore.c.
.SS "\fBpid_t\fP \fBsempid\fP"
.PP
Definition at line 21 of file semaphore.c.
.SS "int \fBsemval\fP"
.PP
Definition at line 19 of file semaphore.c.
.SS "int \fBstate\fP"
.PP
Definition at line 20 of file semaphore.c.
.SS "\fBsemQueue_t\fP* \fBwaitQueue\fP"
.PP
Definition at line 22 of file semaphore.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
