.TH "stdOutTTY" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdOutTTY \- 
.PP
The tty stdout struct.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKeycode\fP * \fBstdOutBuffer\fP"
.br
.ti -1c
.RI "\fBKeycode\fP * \fBbegin\fP"
.br
.ti -1c
.RI "\fBKeycode\fP * \fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The tty stdout struct. 
.PP
Definition at line 242 of file types.h.
.SH "Field Documentation"
.PP 
.SS "\fBKeycode\fP* \fBbegin\fP"
.PP
Definition at line 244 of file types.h.
.SS "\fBKeycode\fP* \fBend\fP"
.PP
Definition at line 245 of file types.h.
.SS "\fBKeycode\fP* \fBstdOutBuffer\fP"
.PP
Definition at line 243 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
