.TH "inc/system.h" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/system.h \- 
.PP
System reboot module.  

.SH SYNOPSIS
.br
.PP
\fC#include 'shell.h'\fP
.br
\fC#include 'io.h'\fP
.br
\fC#include 'types.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrebootSystem\fP (void)"
.br
.RI "\fIReboots the system. \fP"
.in -1c
.SH "Detailed Description"
.PP 
System reboot module. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBsystem.h\fP.
.SH "Function Documentation"
.PP 
.SS "void rebootSystem (void)"
.PP
Reboots the system. 
.PP
Definition at line 12 of file system.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
