.TH "sysTTY" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sysTTY \- 
.PP
The tty system struct.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBqtyTTY\fP"
.br
.ti -1c
.RI "\fBtty_s\fP * \fBlistTTY\fP [MAX_TTY]"
.br
.ti -1c
.RI "\fBtty_t\fP \fBfocusTTY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The tty system struct. 
.PP
Definition at line 270 of file types.h.
.SH "Field Documentation"
.PP 
.SS "\fBtty_t\fP \fBfocusTTY\fP"
.PP
Definition at line 273 of file types.h.
.SS "\fBtty_s\fP* \fBlistTTY\fP[MAX_TTY]"
.PP
Definition at line 272 of file types.h.
.SS "int \fBqtyTTY\fP"
.PP
Definition at line 271 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
