.TH "DESCR_INT" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DESCR_INT \- 
.PP
OS interrupt descriptor struct.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "word \fBoffset_l\fP"
.br
.ti -1c
.RI "word \fBselector\fP"
.br
.ti -1c
.RI "byte \fBcero\fP"
.br
.ti -1c
.RI "byte \fBaccess\fP"
.br
.ti -1c
.RI "word \fBoffset_h\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OS interrupt descriptor struct. 
.PP
Definition at line 350 of file types.h.
.SH "Field Documentation"
.PP 
.SS "byte \fBaccess\fP"
.PP
Definition at line 353 of file types.h.
.SS "byte \fBcero\fP"
.PP
Definition at line 353 of file types.h.
.SS "word \fBoffset_h\fP"
.PP
Definition at line 355 of file types.h.
.SS "word \fBoffset_l\fP"
.PP
Definition at line 351 of file types.h.
.SS "word \fBselector\fP"
.PP
Definition at line 351 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
