.TH "directory" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
directory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpageTable_t\fP \fBtables\fP [PAGE_TABLES_QTY]"
.br
.ti -1c
.RI "\fBpageTable_t\fP \fBpageDirectory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file types.h.
.SH "Field Documentation"
.PP 
.SS "\fBpageTable_t\fP \fBpageDirectory\fP"
.PP
Definition at line 90 of file types.h.
.SS "\fBpageTable_t\fP \fBtables\fP[PAGE_TABLES_QTY]"
.PP
Definition at line 89 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
