.TH "inc/exceptions.h" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/exceptions.h \- 
.PP
Functions related with exception handling.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stdio.h'\fP
.br
\fC#include 'kasm.h'\fP
.br
\fC#include 'kc.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include 'ttys.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBloadExceptionHandlers\fP ()"
.br
.RI "\fILoads the handler of the exception that was produced. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions related with exception handling. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBexceptions.h\fP.
.SH "Function Documentation"
.PP 
.SS "void loadExceptionHandlers ()"
.PP
Loads the handler of the exception that was produced. 
.PP
Definition at line 273 of file exceptions.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
