.TH "FILE" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FILE \- 
.PP
The \fBFILE\fP struct.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "char * \fBptr\fP"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.ti -1c
.RI "\fBsize_t\fP \fBbufferSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBFILE\fP struct. 
.PP
Definition at line 122 of file types.h.
.SH "Field Documentation"
.PP 
.SS "char* \fBbuffer\fP"
.PP
Definition at line 124 of file types.h.
.SS "\fBsize_t\fP \fBbufferSize\fP"
.PP
Definition at line 127 of file types.h.
.SS "int \fBfd\fP"
.PP
Definition at line 123 of file types.h.
.SS "int \fBflag\fP"
.PP
Definition at line 126 of file types.h.
.SS "char* \fBptr\fP"
.PP
Definition at line 125 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
