.TH "inc/keyboard_buffer.h" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/keyboard_buffer.h \- 
.PP
This is the internal keyboard buffer.  

.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBKEYBOARD_BUFFER_SIZE\fP   256"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the internal keyboard buffer. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBkeyboard_buffer.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define KEYBOARD_BUFFER_SIZE   256"
.PP
Definition at line 13 of file keyboard_buffer.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
