.TH "src/libc.c" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libc.c \- 
.PP
The C library module.  

.SH SYNOPSIS
.br
.PP
\fC#include 'libc.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBk_clear_screen\fP ()"
.br
.RI "\fIBrief. \fP"
.ti -1c
.RI "void \fBsetup_IDT_entry\fP (\fBDESCR_INT\fP *item, byte selector, dword offset, byte access, byte cero)"
.br
.RI "\fIBrief. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The C library module. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBlibc.c\fP.
.SH "Function Documentation"
.PP 
.SS "void k_clear_screen ()"
.PP
Brief. Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.PP
Definition at line 18 of file libc.c.
.SS "void setup_IDT_entry (\fBDESCR_INT\fP * item, byte selector, dword offset, byte access, byte cero)"
.PP
Brief. \fBParameters:\fP
.RS 4
\fIitem\fP ParamBrief. 
.br
\fIselector\fP ParamBrief. 
.br
\fIoffset\fP ParamBrief. 
.br
\fIaccess\fP ParamBrief. 
.br
\fIcero\fP ParamBrief.
.RE
.PP
Use: 
.PP
.nf

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
f1() f2() 
.RE
.PP

.PP
Definition at line 42 of file libc.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
