.TH "listWithPrio" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listWithPrio \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "int \fBpQueueDim\fP"
.br
.ti -1c
.RI "\fBNode_t\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBNode_t\fP * \fBlast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file pQueueP.c.
.SH "Field Documentation"
.PP 
.SS "\fBNode_t\fP* \fBfirst\fP"
.PP
Definition at line 27 of file pQueueP.c.
.SS "\fBNode_t\fP* \fBlast\fP"
.PP
Definition at line 28 of file pQueueP.c.
.SS "int \fBpQueueDim\fP"
.PP
Definition at line 26 of file pQueueP.c.
.SS "int \fBpriority\fP"
.PP
Definition at line 25 of file pQueueP.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
