.TH "process_t" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
process_t \- 
.PP
The process struct.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpid_t\fP \fBpid\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBppid\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBgid\fP"
.br
.ti -1c
.RI "\fBtty_t\fP \fBtty\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBchilds\fP [MAX_CHILDS]"
.br
.ti -1c
.RI "int \fBchildsQty\fP"
.br
.ti -1c
.RI "char \fBname\fP [MAX_PROCESS_NAME+1]"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "\fBFILE\fP * \fBfiles\fP [MAX_FILES]"
.br
.ti -1c
.RI "int \fBrpgPrior\fP"
.br
.ti -1c
.RI "int \fBrpgOld\fP"
.br
.ti -1c
.RI "unsigned \fBtickCounter\fP"
.br
.ti -1c
.RI "double \fBcpuPercent\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBwaitingPid\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBsleepingPid\fP"
.br
.ti -1c
.RI "int \fBwaitedStatus\fP"
.br
.ti -1c
.RI "void * \fBebp\fP"
.br
.ti -1c
.RI "void * \fBesp\fP"
.br
.ti -1c
.RI "void * \fBstack\fP"
.br
.ti -1c
.RI "void * \fBheap\fP"
.br
.ti -1c
.RI "\fBframe_t\fP * \fBsFrame\fP"
.br
.ti -1c
.RI "\fBframe_t\fP * \fBpFrame\fP"
.br
.ti -1c
.RI "\fBframe_t\fP * \fBhFrame\fP"
.br
.ti -1c
.RI "int \fBatomicity\fP"
.br
.ti -1c
.RI "int \fBttyMode\fP"
.br
.ti -1c
.RI "\fBheapStatus\fP \fBdataUmalloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The process struct. 
.PP
Definition at line 143 of file types.h.
.SH "Field Documentation"
.PP 
.SS "int \fBatomicity\fP"
.PP
Definition at line 169 of file types.h.
.SS "\fBpid_t\fP \fBchilds\fP[MAX_CHILDS]"
.PP
Definition at line 148 of file types.h.
.SS "int \fBchildsQty\fP"
.PP
Definition at line 149 of file types.h.
.SS "double \fBcpuPercent\fP"
.PP
Definition at line 156 of file types.h.
.SS "\fBheapStatus\fP \fBdataUmalloc\fP"
.PP
Definition at line 171 of file types.h.
.SS "void* \fBebp\fP"
.PP
Definition at line 162 of file types.h.
.SS "void* \fBesp\fP"
.PP
Definition at line 163 of file types.h.
.SS "\fBFILE\fP* \fBfiles\fP[MAX_FILES]"
.PP
Definition at line 152 of file types.h.
.SS "\fBpid_t\fP \fBgid\fP"
.PP
Definition at line 146 of file types.h.
.SS "void* \fBheap\fP"
.PP
Definition at line 165 of file types.h.
.SS "\fBframe_t\fP* \fBhFrame\fP"
.PP
Definition at line 168 of file types.h.
.SS "int \fBlevel\fP"
.PP
Definition at line 158 of file types.h.
.SS "char \fBname\fP[MAX_PROCESS_NAME+1]"
.PP
Definition at line 150 of file types.h.
.SS "\fBframe_t\fP* \fBpFrame\fP"
.PP
Definition at line 167 of file types.h.
.SS "\fBpid_t\fP \fBpid\fP"
.PP
Definition at line 144 of file types.h.
.SS "\fBpid_t\fP \fBppid\fP"
.PP
Definition at line 145 of file types.h.
.SS "int \fBpriority\fP"
.PP
Definition at line 157 of file types.h.
.SS "int \fBrpgOld\fP"
.PP
Definition at line 154 of file types.h.
.SS "int \fBrpgPrior\fP"
.PP
Definition at line 153 of file types.h.
.SS "\fBframe_t\fP* \fBsFrame\fP"
.PP
Definition at line 166 of file types.h.
.SS "\fBpid_t\fP \fBsleepingPid\fP"
.PP
Definition at line 160 of file types.h.
.SS "void* \fBstack\fP"
.PP
Definition at line 164 of file types.h.
.SS "int \fBstate\fP"
.PP
Definition at line 151 of file types.h.
.SS "unsigned \fBtickCounter\fP"
.PP
Definition at line 155 of file types.h.
.SS "\fBtty_t\fP \fBtty\fP"
.PP
Definition at line 147 of file types.h.
.SS "int \fBttyMode\fP"
.PP
Definition at line 170 of file types.h.
.SS "int \fBwaitedStatus\fP"
.PP
Definition at line 161 of file types.h.
.SS "\fBpid_t\fP \fBwaitingPid\fP"
.PP
Definition at line 159 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
