.TH "inc/shell.h" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/shell.h \- 
.PP
The shell process module.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stdio.h'\fP
.br
\fC#include 'video_driver.h'\fP
.br
\fC#include 'unistd.h'\fP
.br
\fC#include 'system.h'\fP
.br
\fC#include 'string.h'\fP
.br
\fC#include 'colors.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include 'process.h'\fP
.br
\fC#include 'uMalloc.h'\fP
.br
\fC#include 'bin.h'\fP
.br
\fC#include 'schedule.h'\fP
.br
\fC#include 'bttlship.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshell\fP (void)"
.br
.RI "\fIThe function that runs the shell application. \fP"
.ti -1c
.RI "int \fBinitGlobalDataShell\fP (void)"
.br
.RI "\fIInitializes the data structures for the shells. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The shell process module. 

\fBAuthor:\fP
.RS 4
Luciano Zemin, Nicolás Magni, Nicolás Purita 
.RE
.PP

.PP
Definition in file \fBshell.h\fP.
.SH "Function Documentation"
.PP 
.SS "int initGlobalDataShell (void)"
.PP
Initializes the data structures for the shells. \fBReturns:\fP
.RS 4
0 on success, -1 on error. 
.RE
.PP

.PP
Definition at line 17 of file shell.c.
.SS "int shell (void)"
.PP
The function that runs the shell application. 
.PP
Definition at line 497 of file shell.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
