.TH "shMem" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shMem \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBshmid\fP"
.br
.ti -1c
.RI "\fBkey_t\fP \fBkey\fP"
.br
.ti -1c
.RI "int \fBshMemSize\fP"
.br
.ti -1c
.RI "\fBframe_t\fP * \fBshMemFrame\fP"
.br
.ti -1c
.RI "unsigned int \fBshMemP\fP"
.br
.ti -1c
.RI "\fBkey_t\fP \fBsemid\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "int \fBpermFlags\fP"
.br
.ti -1c
.RI "int \fBappnProcessesAmm\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBappnProcessesPids\fP [MAX_SHMAPPN]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file shMemory.c.
.SH "Field Documentation"
.PP 
.SS "int \fBappnProcessesAmm\fP"
.PP
Definition at line 25 of file shMemory.c.
.SS "\fBpid_t\fP \fBappnProcessesPids\fP[MAX_SHMAPPN]"
.PP
Definition at line 26 of file shMemory.c.
.SS "\fBkey_t\fP \fBkey\fP"
.PP
Definition at line 18 of file shMemory.c.
.SS "int \fBpermFlags\fP"
.PP
Definition at line 24 of file shMemory.c.
.SS "\fBkey_t\fP \fBsemid\fP"
.PP
Definition at line 22 of file shMemory.c.
.SS "\fBframe_t\fP* \fBshMemFrame\fP"
.PP
Definition at line 20 of file shMemory.c.
.SS "unsigned int \fBshMemP\fP"
.PP
Definition at line 21 of file shMemory.c.
.SS "int \fBshMemSize\fP"
.PP
Definition at line 19 of file shMemory.c.
.SS "int \fBshmid\fP"
.PP
Definition at line 17 of file shMemory.c.
.SS "int \fBstate\fP"
.PP
Definition at line 23 of file shMemory.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
