.TH "stdInTTY" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdInTTY \- 
.PP
The tty stdin struct.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKeycode\fP * \fBstdInBuffer\fP"
.br
.ti -1c
.RI "int \fBwriteOffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The tty stdin struct. 
.PP
Definition at line 233 of file types.h.
.SH "Field Documentation"
.PP 
.SS "\fBKeycode\fP* \fBstdInBuffer\fP"
.PP
Definition at line 234 of file types.h.
.SS "int \fBwriteOffset\fP"
.PP
Definition at line 235 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
