.TH "tty_s" 3 "18 May 2010" "Version 1.0" "flying-high" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tty_s \- 
.PP
The \fBtty_s\fP struct.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtty_t\fP \fBttyId\fP"
.br
.ti -1c
.RI "\fBstdInTTY\fP * \fBstdIn\fP"
.br
.ti -1c
.RI "\fBstdOutTTY\fP * \fBstdOut\fP"
.br
.ti -1c
.RI "int \fBhasScrolled\fP"
.br
.ti -1c
.RI "\fBpid_t\fP \fBfocusProcess\fP"
.br
.ti -1c
.RI "int \fBwritePointer\fP"
.br
.ti -1c
.RI "int \fBwriteCol\fP"
.br
.ti -1c
.RI "int \fBwriteRow\fP"
.br
.ti -1c
.RI "int \fBreadPointer\fP"
.br
.ti -1c
.RI "int \fBreadCol\fP"
.br
.ti -1c
.RI "int \fBreadRow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBtty_s\fP struct. 
.PP
Definition at line 252 of file types.h.
.SH "Field Documentation"
.PP 
.SS "\fBpid_t\fP \fBfocusProcess\fP"
.PP
Definition at line 257 of file types.h.
.SS "int \fBhasScrolled\fP"
.PP
Definition at line 256 of file types.h.
.SS "int \fBreadCol\fP"
.PP
Definition at line 262 of file types.h.
.SS "int \fBreadPointer\fP"
.PP
Definition at line 261 of file types.h.
.SS "int \fBreadRow\fP"
.PP
Definition at line 263 of file types.h.
.SS "\fBstdInTTY\fP* \fBstdIn\fP"
.PP
Definition at line 254 of file types.h.
.SS "\fBstdOutTTY\fP* \fBstdOut\fP"
.PP
Definition at line 255 of file types.h.
.SS "\fBtty_t\fP \fBttyId\fP"
.PP
Definition at line 253 of file types.h.
.SS "int \fBwriteCol\fP"
.PP
Definition at line 259 of file types.h.
.SS "int \fBwritePointer\fP"
.PP
Definition at line 258 of file types.h.
.SS "int \fBwriteRow\fP"
.PP
Definition at line 260 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for flying-high from the source code.
