bin.c
process_t* processTable
void init(void *args)
This functions initialize the welcome process, all the shells and goodbye process. If you kill the process init the system will be rebooted.
args Use: initMultitasker(init);
References ATOMIC, createProcess, FOREGROUND, getpid, getProcessTable, goodbye, MAX_TTY, NULL, puts, rebootSystem, setProcessAtomicity, setTty, setTTYMode, shell, TTY_CANONICAL, UNATOMIC, wait, welcome.
Referenced by kernel_main.
void top(char *args)
This function show what percentage of the microprocessor it is using each process. When you write the command top in the shell, the process top will be created.
args Use: createProcess("top",(void(*)(void*))top,NULL,FOREGROUND);
References ATOMIC, BLOCKED, clearProcessesTicks, clearTTYScreen, process_t::dataUmalloc, DEAD, doubleToString, getpid, getProcessTable, heapStatus::mallocMem, MAX_PROCESS, putchar, puti, puts, READY, refreshProcessesCPUs, RUNNING, SCREEN_WIDTH, setProcessAtomicity, setTTYCursorPosition, strlen, TERMINATED, UNATOMIC, WAITING_CHILD, WAITING_PID, WAITING_TIME.
void welcome()
This function just prints the welcome message to Flying-High OS.
Use: createProcess("welcome",(void(*)(void*))welcome,NULL,FOREGROUND)
References clearTTYScreen, initGlobalDataShell, puts, TICKS_PER_SECOND, upTime.
Referenced by init.
void goodbye()
This function just says goodbye and reboots the system.
Use: createProcess("goodbye",(void(*)(void*))goodbye,NULL,FOREGROUND);
References clearTTYScreen, puts, TICKS_PER_SECOND, upTime.
Referenced by init.
void printA()
This function prints infinite A letters.
Use: createProcess("printA",(void(*)(void*))printA,NULL,FOREGROUND)
References putchar.
void printB()
This functions prints infinite A letters.
Use: createProcess("printB",(void(*)(void*))printB,NULL,FOREGROUND)
References putchar.
void nothing()
This function only consumes the microprocessor.
Use: createProcess("nothing",(void(*)(void*))nothing,NULL,FOREGROUND)
References getchar.
void pageFault()
This function generates a page fault exception.
Use: createProcess("pageFault",(void(*)(void*))pageFault,NULL,FOREGROUND)
References process_t::dataUmalloc, getpid, heapStatus::mallocMem, puts, putx.