bttlship.h
N_X
Referenced by draw_hz, draw_vt, genBattle, getInput, recount, showBattle, showRow.
N_Y
Referenced by draw_hz, draw_vt, genBattle, getInput, recount, showBattle.
N_Z
Referenced by genBattle.
N_SHIPS
Referenced by genBattle.
INP_NONE
Referenced by battleship, getInput.
INP_YX
Referenced by getInput.
LOCK
Referenced by battleship.
UNLOCK
Referenced by battleship.
WAIT2
Referenced by battleship.
NOTIFY2
Referenced by battleship.
FLG_P1
Referenced by bomb, draw_hz, draw_vt, recount, showBattle.
FLG_P2
Referenced by bomb, draw_hz, draw_vt, recount, showBattle.
FLG_SEEN0
Referenced by showBattle.
FLG_SEEN1
Referenced by showBattle.
FLG_BOMBD
Referenced by bomb, recount, showBattle.
FLG_SPLSH
Referenced by bomb, showBattle.
typedef struct S_TABLE S_TABLE
void cleanup(key_t shmid, key_t semid)
Destroys the used shared memory and semaphores.
shmid The id of the shared memory segment. semid The id of the semaphore.
References sem_free, shmdt.
void attachTable(S_TABLE **table, key_t shmid, char **shmp)
It attaches itself to the already created memory.
table The adress of the table. shmid The shared memory segment id. shmp The adress where to store the shared memory segment pointer.
References puts, shmat.
Referenced by battleship.
void lockTable(int semx, int block, S_TABLE **tableS)
It decides if it has to lock the table or wait for the opponent. Peform semaphore wait/notifies: ARGUMENTS: semx 0 : table lock semaphore 1 : opponent notify semaphore block 0 : perform notify 1 : perform wait.
semx It is the parameter to decide what have to do with semaphore block It decides what have to do with the table tableS The adress of the table.
References sem_signal, sem_wait, S_TABLE::semid, S_TABLE::waitSemid.
void recount(S_TABLE **tableS, int *flg_game_over)
It counts the amount of bombs that the player has left.
tableS The address of the table. flg_game_over The adress of the game status.
References S_TABLE::bsites, S_TABLE::flg, FLG_BOMBD, FLG_P1, FLG_P2, N_X, N_Y, S_TABLE::player, S_TABLE::sea.
Referenced by showBattle.
void bomb(int x, int y, S_TABLE **tableS)
It puts the bomb on a specific position of the table.
x The row of the table y The column of the table tableS The address of the table.
References S_TABLE::flg, FLG_BOMBD, FLG_P1, FLG_P2, FLG_SPLSH.
Referenced by battleship.
int getInput(int *px, int *py, S_TABLE **table)
It obtains the the row and the column of the table from STDIN.
px The row of the table py The column of the table table The address of the table.
References EOF, getchar, getpid, getTty, INP_NONE, INP_YX, N_X, N_Y, putchar, puts, waitTty.
Referenced by battleship.
int draw_hz(int sx, int sy, int z, int who, S_TABLE **tableS)
It draws the horizontal ship.
sx Inner use. sy Inner use. z Inner use. who Iner use. tableS The address of the table.
References S_TABLE::flg, FLG_P1, FLG_P2, N_X, N_Y, S_TABLE::sea.
Referenced by genBattle.
int draw_vt(int sx, int sy, int z, int who, S_TABLE **tableS)
It draws the horizontal ship.
sx Inner use. sy Inner use. z Inner use. who Inner use. tableS The address of the table.
References S_TABLE::flg, FLG_P1, FLG_P2, N_X, N_Y, S_TABLE::sea.
Referenced by genBattle.
void genBattle(S_TABLE **tableS)
It generates the table.
tableS The address of the table.
References draw_hz, draw_vt, S_TABLE::flg, memset, N_SHIPS, N_X, N_Y, N_Z, rand, S_TABLE::sea, srand, timeRand.
Referenced by battleship.
void showRow(void)
It prints each row of the table.
References fputc, fputs, N_X, stdout.
Referenced by showBattle.
void showBattle(S_TABLE **tableS, int us, int them, int *flg_game_over)
It prints the table of the battlehsip.
tableS The address of the table. us Inner use. them Inner use. flg_game_over The address of the game status.
References S_TABLE::bsites, S_TABLE::flg, FLG_BOMBD, FLG_P1, FLG_P2, FLG_SEEN0, FLG_SEEN1, FLG_SPLSH, fputc, N_X, N_Y, S_TABLE::player, putchar, puti, puts, recount, S_TABLE::sea, showRow, stdout.
Referenced by battleship.
int battleship()
It's the main process of the battleship, it generates the whole table and ships.
References attachTable, BLOCK, bomb, EOF, genBattle, getchar, getInput, getpid, getTty, INP_NONE, IPC_PRIVATE, LOCK, MAX_PROCESS, NOTIFY2, NULL, S_TABLE::pid, S_TABLE::player, putchar, puti, puts, refreshScreen, refreshStdout, sem_get, S_TABLE::semid, shmget, showBattle, srand, UNLOCK, WAIT, WAIT2, S_TABLE::waitSemid, waitTty.