exceptions.c
typedef struct registers registers_t
DESCR_INT idt[][]
void _divide_e_hand()
Referenced by loadExceptionHandlers.
void _debug_e_hand()
Referenced by loadExceptionHandlers.
void _nmi_e_hand()
Referenced by loadExceptionHandlers.
void _break_point_e_hand()
Referenced by loadExceptionHandlers.
void _overflow_e_hand()
Referenced by loadExceptionHandlers.
void _bounds_check_e_hand()
Referenced by loadExceptionHandlers.
void _invalid_opcode_e_hand()
Referenced by loadExceptionHandlers.
void _copro_unavailable_e_hand()
Referenced by loadExceptionHandlers.
void _double_fault_e_hand()
void _invalid_tss_e_hand()
void _segment_not_present_e_hand()
Referenced by loadExceptionHandlers.
void _stack_e_hand()
Referenced by loadExceptionHandlers.
void _general_protection_e_hand()
Referenced by loadExceptionHandlers.
void _page_fault_e_hand()
Referenced by loadExceptionHandlers.
void _coprocessor_e_hand()
Referenced by loadExceptionHandlers.
static void panic(char *msg, registers_t regs)
void handleException(registers_t regs)
References getFocusedTTY, getpid, kill, puts, refreshTTY, signalTty.
Referenced by boundsCheckExceptionHandler, breakPointExceptionHandler, coprocessorUnavailableExceptionHandler, debugExceptionHandler, divideExceptionHandler, doubleFaultExceptionHandler, generalProtectionExceptionHandler, invalidOpcodeExceptionHandler, invalidTSSExceptionHandler, NMIExceptionHandler, overflowExceptionHandler, pageFaultExceptionHandler, segmentNotPresentExceptionHandler, stackExceptionHandler.
void divideExceptionHandler(registers_t regs)
References handleException.
void debugExceptionHandler(registers_t regs)
References handleException.
void NMIExceptionHandler(registers_t regs)
References handleException.
void breakPointExceptionHandler(registers_t regs)
References handleException.
void overflowExceptionHandler(registers_t regs)
References handleException.
void boundsCheckExceptionHandler(registers_t regs)
References handleException.
void invalidOpcodeExceptionHandler(registers_t regs)
References handleException.
void coprocessorUnavailableExceptionHandler(registers_t regs)
References handleException.
void doubleFaultExceptionHandler(registers_t regs)
References handleException.
void invalidTSSExceptionHandler(registers_t regs)
References handleException.
void segmentNotPresentExceptionHandler(registers_t regs)
References handleException.
void stackExceptionHandler(registers_t regs)
References handleException.
void generalProtectionExceptionHandler(registers_t regs)
References handleException.
void pageFaultExceptionHandler(registers_t regs)
References registers::error, handleException, puts, putx.
void coprocessorExceptionHandler(registers_t regs)
void loadExceptionHandlers()
Loads the handler of the exception that was produced.
References _bounds_check_e_hand, _break_point_e_hand, _copro_unavailable_e_hand, _coprocessor_e_hand, _debug_e_hand, _divide_e_hand, _general_protection_e_hand, _invalid_opcode_e_hand, _nmi_e_hand, _overflow_e_hand, _page_fault_e_hand, _segment_not_present_e_hand, _stack_e_hand, ACS_INT, dword, setup_IDT_entry.
Referenced by kernel_main.