int80.h
void * int80(int eax, void *ebx, void *ecx, void *edx)
copy the parameters to the processor registers.
eax eax register. ebx ebx register. ecx ecx register. edx edx register. The value returned by the function that the int 80 invoked.
Referenced by exit, getLevel, getpid, getppid, getPriority, getTty, getTTYFocusedProcess, getTTYMode, kill, memmap, sem_free, sem_get, sem_signal, sem_wait, setLevel, setPriority, setProcessAtomicity, setTty, setTTYFocusedProcess, setTTYMode, shmat, shmdt, shmget, time, upTime, wait, waitpid.
void * int80ext(int eax, void *ebx, void *ecx, void *edx, void *edi, void *esi)
copy the parameters to the processor registers.
eax eax register. ebx ebx register. ecx ecx register. edx edx register. edi edi register. esi esi register. The value returned by the function that the int 80 invoked.
Referenced by createProcess.