int_handlers.h
void _int_08_handler(void)
This function handles the timer tick interrupt.
Referenced by kernel_main.
void _int_80_handler(void)
This function handles the kernel system calls. Posible system calls: _SYS_WRITE _SYS_READ This rutine must be load into the IDT in the position 0x80.
Referenced by kernel_main.
void _int_09_handler(void)
This function handles the keyboard interrupt.
Referenced by kernel_main.