kasm.h
unsigned int _read_msw()
Brief.
Use: f1() f2()
void _lidt(IDTR *idtr)
Brief.
idtr ParamBrief. Use: f1() f2()
Referenced by kernel_main.
void _mascaraPIC1(byte mascara)
Brief.
mascara ParamBrief. Use: f1() f2()
Referenced by kernel_main.
void _mascaraPIC2(byte mascara)
Brief.
mascara ParamBrief. Use: f1() f2()
Referenced by kernel_main.
void _Cli(void)
Brief.
Use: f1() f2()
Referenced by kernel_main.
void _Sti(void)
Brief.
Use: f1() f2()
Referenced by _sysExit, kernel_main.
void _debug(void)
Brief.
Use: f1() f2()
unsigned getCodeSegment()
Brief.
Use: f1() f2()