memModule.c
directory_t* kernelDir
void* kernelHeap
frame_t* kernelFrame
framesTable_t framesTable
void* getKernelHeap()
Referenced by _sys_memmap.
void loadCR3()
Loads the CR3 into the processor register.
Referenced by initPaging.
int initPaging()
Initializes the pagination and turns it on.
0 on success, -1 on error.
References FALSE, FIRST_KERNEL_TABLE, getFrame, initKernelTable, initMallocTable, initPage, KERNEL_TABLES_QTY, loadCR3, memset, PAGE_TABLES_QTY, setKernelHeapPresence, TOTAL_FRAMES_QTY, TRUE.
Referenced by kernel_main.
void setKernelHeapPresence(int state)
Sets the presence bit of the kernel heap pages according to the given parameter.
state True or False.
References setFramePresence.
Referenced by decreaseKernelDepth, increaseKernelDepth, initPaging.
void initPage(page_t *page, int isKernel)
Initializes the given page with according permissions.
page A pointer to the page. isKernel Permissions, True or False.
References TRUE.
Referenced by allocKPage, allocMPage, initPaging.
int allocKPage(page_t *kernelPage)
Allocs a Page for the kernel.
kernelPage A pointer to the page. 0 on success, -1 on error.
References initPage, KERNEL_SPACE, PAGE_SIZE, TRUE.
Referenced by initKernelTable.
int initKernelTable(pageTable_t kernelTable)
Initializes a kernel page table.
kernelTable The table to be initialized. 0 on success, -1 on error.
References allocKPage, PAGE_ENTRIES_PER_TABLE.
Referenced by initPaging.
int allocMPage(page_t *mallocPage)
Allocs a Page for the malloc section.
mallocPage A pointer to the page. 0 on success, -1 on error.
References FALSE, initPage, MALLOC_SPACE, PAGE_SIZE.
Referenced by initMallocTable.
int initMallocTable(pageTable_t mallocTable, int dirIndex)
Initializes a malloc page table.
dirIndex Reserved. mallocTable The table to be initialized. 0 on success, -1 on error.
References allocMPage, PAGE_ENTRIES_PER_TABLE, PAGES_PER_FRAME.
Referenced by initPaging.
void setFramePresence(frame_t *frame, int state)
Sets the presence bit of the pages from the given frame to the given state.
frame A pointer to the frame. state True or False.
References PAGES_PER_FRAME.
Referenced by _sys_create_process, _sys_shmget, multitasker, setKernelHeapPresence.
frame_t* getFrame()
Gets a free frame.
A pointer to a frame.
References NULL, TOTAL_FRAMES_QTY, TRUE.
Referenced by _sys_create_process, _sys_shmget, initPaging.
int freeFrame(frame_t *frame)
Frees the given frame.
frame A pointer to the frame. 0 on success, -1 on error.
References FALSE.