process.c
process_t processTable[MAX_PROCESS][MAX_PROCESS]
process_t* runningProcess
process_t* initProcess
void* memmap(int isKernel)
Brief.
isKernel ParamBrief. Description. Use: f1() f2()
References _SYS_MEMMAP, int80, NULL.
pid_t createProcess(char *name, pfunc_t main, void *args, int level)
Creates a new process into the system and sets it ready to run. The process will be created in unatomic mode(preemptive mode) and with tty -1.
name The process' name main The process' main function. Must Not Be NULL. args A pointer to an argument list. level FOREGROUND or BACKGROUND. The new process' pid or -1 in case of error.
References _SYS_CREATE, int80ext, NULL.
Referenced by init, initMultitasker.
void exit(int status)
This function terminates the calling process and status is returned to whom is waiting for the calling process to exit.
status The process' exit status.
References _SYS_EXIT, int80, NULL.
tty_t setTty(pid_t pid, tty_t tty)
Sets the given process tty id.
pid The process' pid whose tty id will be set. tty The tty id to be set. 0 on success, -1 on error. Use: f1() f2()
References _SYS_SET_TTY, int80, NULL.
Referenced by init.
tty_t getTty(pid_t pid)
Retrieves the given process pid's tty.
pid The pid of the process. The tty id. setTty()
References _SYS_GET_TTY, int80, NULL.
Referenced by battleship, getInput, shell.
tty_t setTTYFocusedProcess(pid_t pid, tty_t tty)
Sets the given tty focused process with the given pid process.
pid The process to be set as focused process. tty The tty whose focused process will be set. 0 on success, -1 on error. getTTYFocusedProcess()
References _SYS_SET_TTY_FP, int80, NULL.
pid_t getTTYFocusedProcess(tty_t tty)
Retrieves the given tty focused process pid.
tty The tty id. The pid of the tty focused process. setTTYFocusedProcess()
References _SYS_GET_TTY_FP, int80, NULL.
pid_t getpid(void)
Retrieves the calling process' pid.
The calling process' pid.
References _SYS_GET_PID, int80, NULL.
Referenced by _sys_sem_get, _sys_shm_detach, _sys_shmat, battleship, getInput, handleException, init, pageFault, shell, top.
pid_t getppid()
Retrieves the calling process' parent pid.
The calling process' parent pid.
References _SYS_GET_PPID, int80, NULL.
int wait(int *status)
Blocks the calling process until a child returns.
status A pointer where to store the return state of the child process. Returns the pid of the child process that recently returned. waitpid()
References _SYS_WAIT, int80, NULL.
Referenced by init.
int waitpid(pid_t pid, int *status)
This function blocks the calling process until the given pid child returns.
pid The pid of the child process to wait. status A pointer where to store the child process return status. The pid of the child process. wait()
References _SYS_WAIT_PID, int80, NULL.
int kill(int pid)
Kills the given pid process.
pid The pid of the process to be killed. 0 on success, -1 on error.
References _SYS_KILL, int80, NULL.
Referenced by handleException, refreshKeyboardBufferTTY.
int setTTYMode(pid_t pid, int mode)
Sets the tty mode of the given pid process.
pid The pid of the process whose tty mode will be changed. mode The tty mode: TTY_CANONICAL or TTY_RAW. 0 on success, -1 on error. getTTYMode()
References _SYS_SET_TTY_MODE, int80, NULL.
Referenced by init.
int getTTYMode(pid_t pid)
Retrieves the given pid process tty mode.
pid The pid of the process whose tty mode will be retrieved. The tty mode. setTTYMode()
References _SYS_GET_TTY_MODE, int80, NULL.
int setLevel(int level)
Sets the calling process level.
level FOREGROUND or BACKGROUND. TRUE on success, FALSE on error. getLevel()
References _SYS_SET_LEVEL, int80, NULL.
int getLevel()
Retrieves the calling process' level.
The calling process' level. setLevel()
References _SYS_GET_LEVEL, int80, NULL.
int getPriority()
Retrieves the calling process' priority.
The calling process' priority. setPriority()
References _SYS_GET_PRIO, int80, NULL.
int setPriority(pid_t pid, int prio)
Sets the pid process priority.
pid The pid of the process whose priority will be changed. prio The priority to be set. prio on success, -1 on error. getPriority()
References _SYS_SET_PRIO, int80, NULL.
unsigned time(void)
Retrieves the amount of miliseconds that the calling process' had the processor.
The amount of miliseconds that the calling process' had the processor.
References _SYS_TIME, int80, NULL.
unsigned upTime()
Retrieves the amount of ticks since the system boot.
The amount of ticks since the system boot.
References _SYS_UPTIME, int80, NULL.
Referenced by goodbye, timeRand, welcome.
int setProcessAtomicity(pid_t pid, int atomic)
Sets the given pid process' atomicity.
pid The pid of the process whose atomicity will be set. atomic ATOMIC or UNATOMIC. 0 on success, -1 on error.
References _SYS_SET_ATOM, int80, NULL.
Referenced by init, shell, top.