queue.c
Keycode* keyboardBuffer
int curr
int tail
int charEnque(Keycode elem)
elem This function receive the ASCII code of the key to enqueue in the buffer. TRUE if the key was added or FALSE if the buffer is FULL
References KEYBOARD_BUFFER_SIZE, keyboardBuffer, TRUE.
Referenced by keyboard_driver.
Keycode charDeque(void)
Dequeue an element while the buffer is not Empty.
The keycode
References KEYBOARD_BUFFER_SIZE, keyboardBuffer.
Referenced by refreshKeyboardBufferTTY.
int kbBufferIsEmpty(void)
return if the buffer is empty
TRUE if it's empty, FALSE if not
Referenced by refreshKeyboardBufferTTY.