rand.h
RAND_MAX
Referenced by rand.
unsigned int timeRand()
This function loads the amount of ticks. It uses a system call.
The amount of tick Use: srand(timeRand()); _system_uptime
References upTime.
Referenced by genBattle.
int rand()
Generates a random number with a linear equation.
A random number Use: intran=rand();
References RAND_MAX.
Referenced by genBattle.
void srand(unsigned int seedP)
Sets the seed to generate random numbers.
seedP The seed to be set. Use: srand(timeRand());
Referenced by battleship, genBattle.