semaphore.h
BLOCK
Referenced by _sys_sem_get, _sys_shmget, battleship.
WAIT
Referenced by _sys_sem_get, battleship.
MAX_SEMS
Referenced by _sys_sem_get, initializeSemaphores.
UNUSED
Referenced by _sys_sem_free, _sys_sem_get, initializeSemaphores.
USED
Referenced by _sys_sem_get.
key_t sem_get(int mode)
Gets a semaphore for the given mode.
mode Block or Wait modes. The key of the semaphore. sem_free()
References _SYS_SEM_GET, int80, NULL.
Referenced by _sys_shmget, battleship.
void sem_free(key_t semid)
Frees up the given semid semaphore.
semid The id of the semaphore. sem_get()
References _SYS_SEM_FREE, int80, NULL.
Referenced by cleanup.
void sem_wait(key_t sem)
Waits for the semaphore to be available..
sem The semaphore id. sem_signal()
References _SYS_SEM_WAIT, int80, NULL.
Referenced by lockTable.
void sem_signal(key_t sem)
Signals the given semaphore to enable it for other users.
sem The semaphore id. sem_free()
References _SYS_SEM_SIGNAL, int80, NULL.
Referenced by lockTable.
void initializeSemaphores()
Initializes all semaphores.
References semQueue::actPos, MAX_SEMS, semQueue::pidsQty, semaphore::semid, semaphore::sempid, semaphore::semval, semaphore::state, UNUSED, semaphore::waitQueue.
Referenced by kernel_main.