shMemory.h
IPC_RMID
IPC_SET
IPC_STAT
IPC_CREAT
IPC_PRIVATE
Referenced by battleship.
MAX_SHMEMS
Referenced by _sys_shm_detach, _sys_shmat, _sys_shmget, initializeShMems.
MAX_SHMAPPN
Referenced by _sys_shm_detach, _sys_shmat, initializeShMems.
int shmget(key_t key, int size)
Gets a new shared memory with the given key and size.
key The key for the shared memory segment. size The shared memory size. The id of the shared memory on success, -1 on error. shmat() shmdt()
References _SYS_SHMGET, int80, NULL.
Referenced by battleship.
char * shmat(int shmid, key_t *semid)
Attaches the current process to the shmid shared memory.
shmid The id of the shared memory segment. semid A pointer to a key_t variable where to store the shared memory inner semaphore id. A pointer to the shared memory space. shmget() shmdt()
References _SYS_SHMAT, int80, NULL.
Referenced by attachTable.
int shmdt(int shmid)
Detaches the current process form the shmid shared memory segment.
shmid The id of the shared memory segment. 0 on success, -1 on error. shmget() shmat()
References _SYS_SHM_DETACH, int80, NULL.
Referenced by cleanup.
void initializeShMems()
Initializes all the shared memories.
References _READ, _WRITE, shMem::appnProcessesAmm, shMem::appnProcessesPids, FREE, shMem::key, MAX_SHMAPPN, MAX_SHMEMS, NULL, shMem::permFlags, shMem::semid, shMem::shMemFrame, shMem::shMemP, shMem::shMemSize, shMem::shmid, shMem::state.
Referenced by kernel_main.