stdio.c
NIBBLES_PER_INT
Referenced by fputx.
int fputi(int i, FILE *stream)
Writes the given integer to the given stream.
i The integer to write. stream The stream where to write to. 0 on success, -1 on error.
References fputs, intToString, memset.
int fputx(int num, FILE *stream)
Writes the given integer as in hexadecimal format into the given stream.
num The number to bw written. stream The stream where to write the number to. 0 on success, -1 on error.
References fputs, memset, NIBBLES_PER_INT.
int fputc(int c, FILE *stream)
Writes the given character to the given stream.
c The character ascii to be written. stream The stream where to write the character to. 0 on success, -1 on error. fgetc()
References EOF, fwrite, NULL.
Referenced by showBattle, showRow.
int fgetc(FILE *stream)
Reads a character ascii from the given stream and returns it.
stream The stream where to read the character from. The ascii from the read character. fputc()
References EOF, fread, NULL.
int fputs(const char *s, FILE *stream)
Writes the given string to the given stream.
s A null terminate string to be written. stream The stream where to write the string. 0 on success, -1 on error. fgets()
References EOF, fwrite, NULL, strlen.
Referenced by fputi, fputx, showRow.
char* fgets(char *s, int size, FILE *stream)
Reads a string of the given size from the given stream.
s A pointer to the buffer where to write the string to. size The ammount of bytes to be read. stream The stream where to read the string from. 0 on success, -1 on error. fputs()
References EOF, fread, NULL.
void flush(FILE *stream)
Flushes the given stream.
stream The stream to be flushed.
References FILE::buffer, NULL, FILE::ptr.