sysProcess.c
unsigned int tickCount
Referenced by _sys_uptime.
process_t processTable[MAX_PROCESS][MAX_PROCESS]
process_t* runningProcess
Referenced by shell.
process_t* initProcess
process_t* nextProcess
int mtActivated
pid_t ttyRestPlace[MAX_TTY][MAX_TTY]
FILE fileSystems[MAX_PROCESS][MAX_FILES][MAX_PROCESS][MAX_FILES]
char fileBuffers[MAX_PROCESS][MAX_FILES][SCREEN_SIZE][MAX_PROCESS][MAX_FILES][SCREEN_SIZE]
Referenced by initMultitasker.
int qtyProccessTable
int isMTActivated()
Checks wether the multitasker is activated or not.
True if it's activated, False if not.
static void freeTerminatedProcesses(void)
int initMultitasker(pfunc_t init)
Initializes the multitasker and creates the init process.
init A pointer to the init function. 0 on success, -1 on error. multitasker()
References _READ, _WRITE, BACKGROUND, FILE::buffer, FILE::bufferSize, process_t::childsQty, createProcess, DEAD, FALSE, FILE::fd, fileBuffers, process_t::files, FILE::flag, MAX_FILES, MAX_TTY, process_t::pid, process_t::priority, FILE::ptr, process_t::rpgOld, SCREEN_SIZE, process_t::state, TRUE.
Referenced by kernel_main.
void multitasker(void)
References ATOMIC, process_t::atomicity, process_t::ebp, process_t::esp, FALSE, FOREGROUND, getNextTask, process_t::hFrame, process_t::level, NULL, process_t::pid, READY, RUNNING, setFramePresence, process_t::sFrame, process_t::state, sysSetTTYFocusedProcess, process_t::tickCounter, TRUE, process_t::tty.
static void wakeUpProcess(process_t *process, int status)
void sysSelfBlock()
Blocks the calling process.
sysUnblock()
References BLOCKED, forceMultitasker, process_t::state.
Referenced by _sys_sem_wait.
int sysUnblock(pid_t pid)
Unblocks the given pid process.
pid The pid of the process to be unlocked. 0 on success, -1 on error. sysSelfBlock()
References BLOCKED, READY, process_t::state.
Referenced by _sys_sem_signal.
void waitTty(tty_t tty)
Blocks the calling process until it's tty is signaled.
tty The tty of the process to be blocked. signalTty()
References BLOCKED, forceMultitasker, process_t::pid, process_t::state.
Referenced by battleship, getInput, shell.
void signalTty(tty_t tty)
Signals the given tty so that any blocked process from it can be unblocked.
tty The tty to be signaled. waitTty()
References READY, process_t::state.
Referenced by handleException.
static void alertWaitingProcesses(pid_t pid, int status)
void terminate(pid_t pid, int status)
Terminates the given process with the given status.
pid The pid number from the process to be terminated. status The status upon which the process is being terminated.
References FOREGROUND, MAX_CHILDS, sysSetTTYFocusedProcess, TERMINATED, UNATOMIC.
Referenced by _sys_kill, _sysExit.
void refreshProcessesCPUs()
Refreshes the process comsumption of every process.
clearProcessesTicks()
Referenced by top.
void clearProcessesTicks()
Clears the current tickcount of every process.
refreshProcesses()
Referenced by top.
process_t* getProcessTable(void)
Retrieves the OS process table.
A pointer to the OS process table.
Referenced by init, refreshKeyboardBufferTTY, top.
char* getProcessName(pid_t pid)
Retrieves the given pid process name.
pid The pid from the process whose name to be retrieven. The process' name.
References NULL.