uMalloc.c
static memArea_t* getMem()
void free(void *ap)
Frees up the user memory pointed by ap for futures mallocs.
ap Pointer to the logical memory position that would be freed. malloc() realloc()
References sysFree.
Referenced by freeNode, freePQueue.
void* malloc(size_t nbytes)
returns a continuous segment of user memory. It could return null if there is not enough free space.
nbytes The size of continuous memory that would be returned. The logical user memory to be used. free() realloc()
References sysMalloc.
Referenced by enque, newPQueue.
void* realloc(void *ap, size_t size)
Changes the original size of the continuous memory. If it is possible, it moves the old segment of user memory to a new continuous user memory segment .
ap The old position that would be changed if it's necessary. size The new size of the continuous user memory. A new continuous segment of user memory. free() malloc()
References sysRealloc.