unistd.h
ssize_t write(int fileds, const void *buffer, size_t count)
write() writes "count" bytes from the buffer pointed by "buffer" into the file descripted by the file descriptor "fileds".
fileds the file descriptor for the file where the data is going to be written. buffer pointer to the buffer where the information to be written is hold. count number of bytes that will be written in the file from the buffer. the amount of bytes successfully written in the file or -1 in case of error. Example: char*message="HelloWorld!\n"; write(STDOUT,(constvoid*)message,strlen(message)); read()
Referenced by _sys_fwrite.
ssize_t read(int fileds, void *buffer, size_t count)
read() reads "count" bytes from the file descripted by the file descriptor "fileds" and saves it into the buffer pointed by "buffer"
fileds the file descriptor for the file where the data is going to be read. buffer pointer to the buffer where the information is going to written. count number of bytes that will be written in the buffeer from the file. the amount of bytes that were successfully read from the file or -1 in case of error. Example if(read(STDIN,buffer,VIDEO_SIZE)!=VIDEO_SIZE) printf("Error:videomemorycouldnotberead\n"); write()
Referenced by _sys_fread, refreshStdout.
size_t fread(FILE *stream, void *buffer, size_t count)
Idem to the read() function, but from the given stream.
stream The stream where to read from. buffer A pointer to the buffer where the information is going to written. count Number of bytes that will be written in the buffeer from the file. The amount of bytes that were successfully read from the file or -1 in case of error. Use: if(read(stream,buffer,VIDEO_SIZE)!=VIDEO_SIZE) printf("Error:videomemorycouldnotberead\n"); fwrite()
Referenced by fgetc, fgets.
size_t fwrite(FILE *stream, void *buffer, size_t count)
Idem to the write() function, but to the given stream.
stream The stream where to write to. buffer pointer to the buffer where the information to be written is hold. count number of bytes that will be written in the file from the buffer. The amount of bytes that were successfully read from the file or -1 in case of error. Use: char*message="HelloWorld!\n"; write(stream,(constvoid*)message,strlen(message)); fread()
Referenced by fputc, fputs.