video_driver.c
VGA_MISC_REGISTER
Referenced by initVideo.
VGA_CURSOR_POS_HIGH_PORT
VGA_CURSOR_POS_LOW_PORT
VGA_MAX_SCAN_LINE_REGISTER
Referenced by initVideo.
VGA_CURSOR_START_REGISTER
Referenced by initVideo.
VGA_CURSOR_END_REGISTER
Referenced by initVideo.
VGA_INPUT_STATUS_REGISTER
Referenced by initVideo.
VGA_ADDRESS_DATA_REGISTER
Referenced by initVideo.
VGA_DATA_READ_REGISTER
Referenced by initVideo.
colorMask
getOffset
Referenced by putCharAtFixedPos, putColoredStringAtFixedPos, setCursorPosition.
typedef void(* printFunctionT)(void))(void)
typedef struct indexedBuffer indexedBufferT
short cursorOffset
int cursorRow
int cursorCol
int cursorVisibility
unsigned char* videoMemory
unsigned char videoBuffer[VIDEO_MEMORY_SIZE][VIDEO_MEMORY_SIZE]
unsigned char videoColor
int CRTCAddress
int CRTCData
int vtabStop
int tabStop
static void fillLine(int c)
void printAlarm(void)
Brief.
Use: f1() f2()
void printBackspace(void)
Brief.
Use: f1() f2()
References decCursor, videoBuffer.
void printNewLine(void)
Brief.
Use: f1() f2()
References incCursor.
Referenced by printLineFeed, printVTab.
void printLineFeed(void)
Brief.
Use: f1() f2()
References incCursor, printNewLine.
void printReturn(void)
Brief.
Use: f1() f2()
References decCursor.
void printTab(void)
Brief.
Use: f1() f2()
References incCursor, videoBuffer.
void printVTab(void)
Brief.
Use: f1() f2()
References incCursor, printNewLine.
static int parseCharacter(int c, int offset)
static void scrollScreen()
static void refreshCursor(void)
void initVideo(int cursorEnabled)
Initializes the video driver, by setting the initial cursor position, setting it's visibility, enabling the blinking cursor and defining cursor shape.
cursorEnabled zero to disable the cursor, not zero to enable the cursor.
References inportb, outportb, setCursorVisibility, VGA_ADDRESS_DATA_REGISTER, VGA_CURSOR_END_REGISTER, VGA_CURSOR_START_REGISTER, VGA_DATA_READ_REGISTER, VGA_INPUT_STATUS_REGISTER, VGA_MAX_SCAN_LINE_REGISTER, VGA_MISC_REGISTER.
Referenced by kernel_main.
void refreshScreen(void)
Updates all changes made to video buffer into screen.
References memcpy, VIDEO_MEMORY_SIZE, videoBuffer.
Referenced by battleship, changeFocusTTY, putTTYCharAtPosition, refreshTTY.
void updateColor(void)
Updates the hole screen with actual video color all colors will be changed.
References VIDEO_MEMORY_SIZE, videoBuffer.
int setCursorVisibility(int b)
Sets the cursor's visibility. Zero to turn it off not zero to turn it on.
The actual state of visibility
References inportb, outportb.
Referenced by initVideo.
void incCursor(void)
Increments the position of the cursor by one unit. Automatically resolves new lines and screen scrolling.
References SCREEN_HEIGTH, SCREEN_WIDTH.
Referenced by printColorChar, printLineFeed, printNewLine, printTab, printVTab.
void decCursor(void)
Decrements the position of the cursor by one unit. Automatically resolves jumps to previous lines.
References SCREEN_WIDTH.
Referenced by printBackspace, printReturn.
int setCursorPosition(int row, int col)
Sets the cursor's position.
row the new row position. col the new col position. the offset from the (0,0) including the attribute byte.
References getOffset, SCREEN_HEIGTH, SCREEN_WIDTH.
Referenced by changeFocusTTY, clearTTYScreen, setTTYCursorPosition.
void getCursorPosition(int *row, int *col)
Gets the actual cursor's position.
row a pointer to int where the actual row position will be returned. Must not be NULL. col a pointer to int where the acutal col position will bie returned. Must not be NULL.
References NULL.
int getVideoColor(void)
Gets the actual default video color.
the actual video color code
Referenced by putTTYCharAtPosition, refreshKeyboardBufferTTY.
int setVideoColor(int color)
Set the default video color.
color the new video color code the new video color code
int getVideoTabStop(void)
Gets the video tab stop.
int setVideoTabStop(int num)
Sets the video tab stop.
int getVideoVTabStop(void)
Gets the video vertical tab.
int setVideoVTabStop(int num)
Sets the video vertical tab stop.
void putCharAtCurrentPos(int c, int color)
Puts a character into the video buffer at the current cursor position.
c the character to be putted into the video buffer color the color code of the character
References videoBuffer.
Referenced by putTTYCharAtPosition.
void printChar(int c)
Puts a character into the video buffer at the current position and moves the cursor.
c the character to be putted into the video buffer
References printColorChar.
void printColorChar(int c, int color)
Puts a character into the video buffer at the current position and moves the cursor.
c the character to be putted into the video buffer color the color code of the character.
References incCursor, videoBuffer.
Referenced by printChar.
int putCharAtFixedPos(int c, int color, int row, int col)
Puts a character into the video buffer at a given position.
c the character to be putted into the video buffer color the color code of the character. row the row position where the character will be putted col the col position where the character will be putted
References getOffset, SCREEN_HEIGTH, SCREEN_WIDTH, videoBuffer.
int putColoredStringAtFixedPos(char *s, int *color, int length, int row, int col)
Puts a string at a given position.
s The string to be putted. color a pointer to int with the color codes for each character or NULL to print with the default video color. length ParamDescription. row ParamDescription. col ParamDescription.
References getOffset, NULL, SCREEN_HEIGTH, SCREEN_WIDTH, VIDEO_MEMORY_SIZE, videoBuffer.
void fillScreen(int c)
Fills the screen with a character.
References VIDEO_MEMORY_SIZE, videoBuffer.
Referenced by clearScreen.
void clearScreen(void)
Clears the screen
References fillScreen.
Referenced by changeFocusTTY, clearTTYScreen, kernel_main.