game.c
void recount(S_TABLE **tableS, int *flg_game_over)
It counts the amount of bombs that the player has left.
tableS The address of the table. flg_game_over The adress of the game status.
References S_TABLE::bsites, S_TABLE::flg, FLG_BOMBD, FLG_P1, FLG_P2, N_X, N_Y, S_TABLE::player, S_TABLE::sea.
Referenced by showBattle.
void bomb(int x, int y, S_TABLE **tableS)
It puts the bomb on a specific position of the table.
x The row of the table y The column of the table tableS The address of the table.
References S_TABLE::flg, FLG_BOMBD, FLG_P1, FLG_P2, FLG_SPLSH.
Referenced by battleship.
int getInput(int *px, int *py, S_TABLE **table)
It obtains the the row and the column of the table from STDIN.
px The row of the table py The column of the table table The address of the table.
References EOF, getchar, getpid, getTty, INP_NONE, INP_YX, N_X, N_Y, putchar, puts, waitTty.
Referenced by battleship.
int draw_hz(int sx, int sy, int z, int who, S_TABLE **tableS)
It draws the horizontal ship.
sx Inner use. sy Inner use. z Inner use. who Iner use. tableS The address of the table.
References S_TABLE::flg, FLG_P1, FLG_P2, N_X, N_Y, S_TABLE::sea.
Referenced by genBattle.
int draw_vt(int sx, int sy, int z, int who, S_TABLE **tableS)
It draws the horizontal ship.
sx Inner use. sy Inner use. z Inner use. who Inner use. tableS The address of the table.
References S_TABLE::flg, FLG_P1, FLG_P2, N_X, N_Y, S_TABLE::sea.
Referenced by genBattle.
void genBattle(S_TABLE **tableS)
It generates the table.
tableS The address of the table.
References draw_hz, draw_vt, S_TABLE::flg, memset, N_SHIPS, N_X, N_Y, N_Z, rand, S_TABLE::sea, srand, timeRand.
Referenced by battleship.
void showRow(void)
It prints each row of the table.
References fputc, fputs, N_X, stdout.
Referenced by showBattle.
void showBattle(S_TABLE **tableS, int us, int them, int *flg_game_over)
It prints the table of the battlehsip.
tableS The address of the table. us Inner use. them Inner use. flg_game_over The address of the game status.
References S_TABLE::bsites, S_TABLE::flg, FLG_BOMBD, FLG_P1, FLG_P2, FLG_SEEN0, FLG_SEEN1, FLG_SPLSH, fputc, N_X, N_Y, S_TABLE::player, putchar, puti, puts, recount, S_TABLE::sea, showRow, stdout.
Referenced by battleship.