io.h
VIDEO_MEMORY_ADDRESS
int inportb(int port)
This function grabs the value stored in the given port.
port The desired port number. This function returns an int instance with the value obtained. intvalue; value=inport(0x60); outport()
Referenced by initVideo, keyboard_driver, rebootSystem, setCursorVisibility.
void outportb(int port, int value)
This function stores the given value in the given port.
port Desired port number. value Desired value to set. outport(0x64,0x31) inport()
Referenced by initVideo, rebootSystem, setCursorVisibility.