schedule.c
process_t processTable[MAX_PROCESS][MAX_PROCESS]
process_t* nextProcess
process_t* initProcess
process_t* runningProcess
int qtyProccessTable
int Algorithim
int prevPro
static process_t* roundRobinSchedule()
process_t* rpgSchedule()
This function simulates the RPG scheduling. What this algorithm does, is that when a process achieves the maximum value of RPG, it adds it to a queue. After that the functions just find the oldest process that is waiting to be attended.
The process to be attended Use: if(ALGORITHIM==RPG) returnrpgSchedule();
References checkWhatAreReady, increaseRPGCounter, process_t::rpgPrior.
Referenced by getNextTask.
process_t* getNextTask()
This function returns the next task that should be attended.
The next process Use: changeContext(getNextTask());
References ROUND_ROBIN, rpgSchedule.
Referenced by multitasker.
int checkWhatAreReady(void)
This function checks what processes are ready using the RPG Algorithim.
the index of table process
References MAX_PROCESS, MAX_RPG, READY.
Referenced by rpgSchedule.
void increaseRPGCounter()
This function increases the current rpg value of each process.
References evaluate, MAX_PROCESS, READY, process_t::rpgOld, process_t::rpgPrior.
Referenced by rpgSchedule.
void changeAlgorithimSchedule(void)
This function changes the Algorithm variable, if the current algorithm is RoundRobin it changes to RPG and viceversa.
References puts, ROUND_ROBIN, RPG.