semaphore.c
typedef struct semQueue semQueue_t
typedef struct semaphore semaphore_t
semQueue_t queues[MAX_SEMS][MAX_SEMS]
semaphore_t sems[MAX_SEMS][MAX_SEMS]
static int semIsEmpty(semQueue_t *queue)
static int semEnque(semQueue_t *queue)
static pid_t semDeque(semQueue_t *queue)
void initializeSemaphores()
Initializes all semaphores.
References semQueue::actPos, MAX_SEMS, semQueue::pidsQty, semaphore::semid, semaphore::sempid, semaphore::semval, semaphore::state, UNUSED, semaphore::waitQueue.
Referenced by kernel_main.
key_t sem_get(int mode)
Gets a semaphore for the given mode.
mode Block or Wait modes. The key of the semaphore. sem_free()
References _SYS_SEM_GET, int80, NULL.
Referenced by _sys_shmget, battleship.
void sem_free(key_t semid)
Frees up the given semid semaphore.
semid The id of the semaphore. sem_get()
References _SYS_SEM_FREE, int80, NULL.
Referenced by cleanup.
void sem_wait(key_t sem)
Waits for the semaphore to be available..
sem The semaphore id. sem_signal()
References _SYS_SEM_WAIT, int80, NULL.
Referenced by lockTable.
void sem_signal(key_t sem)
Signals the given semaphore to enable it for other users.
sem The semaphore id. sem_free()
References _SYS_SEM_SIGNAL, int80, NULL.
Referenced by lockTable.
key_t _sys_sem_get(int mode)
References BLOCK, getpid, MAX_SEMS, semaphore::semid, semaphore::sempid, semaphore::semval, semaphore::state, UNUSED, USED, WAIT.
void _sys_sem_free(key_t semid)
References semQueue::actPos, semQueue::pidsQty, semaphore::sempid, semaphore::semval, semaphore::state, UNUSED, semaphore::waitQueue.
int _sys_sem_wait(key_t semid)
References puts, semaphore::semval, sysSelfBlock.
int _sys_sem_signal(key_t semid)
References puts, semaphore::semval, sysUnblock.