stdio.h
EOF
Referenced by battleship, fgetc, fgets, fputc, fputs, getInput, shell.
stdin
stdin stream define.
stdout
stdout stream define.
Referenced by showBattle, showRow.
puts
puts function define.
Referenced by _sys_sem_signal, _sys_sem_wait, attachTable, battleship, changeAlgorithimSchedule, getInput, goodbye, handleException, init, newPQueue, pageFault, pageFaultExceptionHandler, printQueue, shell, showBattle, top, welcome.
putchar
putchar function define.
Referenced by battleship, getInput, printA, printB, showBattle, top.
getchar
getchar function define.
Referenced by battleship, getInput, nothing, shell.
puti
puti function define.
Referenced by battleship, shell, showBattle, top.
putx
putx function define.
Referenced by pageFault, pageFaultExceptionHandler.
process_t* runningProcess
Referenced by shell.
int fputi(int i, FILE *stream)
Writes the given integer to the given stream.
i The integer to write. stream The stream where to write to. 0 on success, -1 on error.
References fputs, intToString, memset.
int fputx(int i, FILE *stream)
Writes the given integer as in hexadecimal format into the given stream.
num The number to bw written. stream The stream where to write the number to. 0 on success, -1 on error.
References fputs, memset, NIBBLES_PER_INT.
int fputs(const char *s, FILE *stream)
Writes the given string to the given stream.
s A null terminate string to be written. stream The stream where to write the string. 0 on success, -1 on error. fgets()
References EOF, fwrite, NULL, strlen.
Referenced by fputi, fputx, showRow.
int fputc(int c, FILE *stream)
Writes the given character to the given stream.
c The character ascii to be written. stream The stream where to write the character to. 0 on success, -1 on error. fgetc()
References EOF, fwrite, NULL.
Referenced by showBattle, showRow.
char * fgets(char *s, int size, FILE *stream)
Reads a string of the given size from the given stream.
s A pointer to the buffer where to write the string to. size The ammount of bytes to be read. stream The stream where to read the string from. 0 on success, -1 on error. fputs()
References EOF, fread, NULL.
int fgetc(FILE *stream)
Reads a character ascii from the given stream and returns it.
stream The stream where to read the character from. The ascii from the read character. fputc()
References EOF, fread, NULL.
void flush(FILE *stream)
Flushes the given stream.
stream The stream to be flushed.
References FILE::buffer, NULL, FILE::ptr.