string.h
char * strncpy(char *dst, const char *source, int n)
Copies the first n bytes from the source string to the dst string.
dst The destination string. source The source string. n The ammount of bytes to be copied. A pointer to the copied string.
int stringHasChar(const char *string, const char c)
Checks wether the given string contains or not the given character.
string The string to be checked. c The character to be checked. True if found, False if not.
References FALSE, strlen, TRUE.
char * strcat(char *dst, const char *src)
Concatenates the src string to the end of the dst string.
dst The destination string. src The source string. A pointer to the concatenated string.
int strlen(const char *str)
Returns the length of the string.
str The string whose length will be calculated. The length of the given string.
Referenced by _sys_create_process, fputs, stringHasChar, strtok, top.
int strcmp(const char *s1, const char *s2)
The strcmp() function compares the two strings s1 and s2.
s1 The first string to be compared. s2 The second string to be compared. It returns an integer less than, equal to, or greater than zero if s1 is found, respectively, to be less than, to match, or be greater than s2.
References NULL.
void * memcpy(void *dest, const void *src, size_t n)
The memcpy() function copies n bytes from memory area src to memory area dest. The memory areas should not overlap.
dest the destination memory address source the source memory address n the amount of bytes to be copied A pointer to the copied memory.
Referenced by _sys_create_process, _sys_read, refreshScreen, sysRealloc.
void * memset(void *dest, int c, size_t n)
The memset() function sets n bytes from the memory area dest with the value of c.
dest Where the memory will be setted. val The value with which the memory will be setted. len The ammount of bytes to be setted. A pointer to the setted memory.
Referenced by _sys_create_process, fputi, fputx, genBattle, initPaging.
int strncmp(const char *s1, const char *s2, size_t n)
The strcmp() function compares the two strings s1 and s2 up to the nth character.
s1 The first string to be compared. s2 The second string to be compared. n The amount of bytes to be taken into acount form each string. It returns an integer less than, equal to, or greater than zero if s1 is found, respectively, to be less than, to match, or be greater than s2.
char * strcpy(char *dst, const char *source)
Copies the source Null terminated string to the dst string.
dst Where to copy the string. source The Null terminated string to be copied. A pointer to the copied string.
char * strtok(char *s, char *tokens)
Gets segments of the given string delimitated by the given tokens.
s The string to be segmentated. tokens The tokens that limitate the segments. A pointer to the current segment.
References NULL, strlen.
int toInt(char *string)
Transforms the given string to an int.
string The string to be parsed. The int value of the string on success, -1 on error.
char * intToString(int num, char *str)
Transforms the given int number to a string.
num The number to be transformed. str A pointer where to write the string. The pointer to the transformed string on success, NULL on error.
References NULL.
Referenced by fputi.
char * doubleToString(double num, char *str)
Idem as intToString, but with double values.
num The double number to be transformed. str A pointer where to store the string. A pointer to the transformed string on success, NULL on error. intToString()
References NULL.
Referenced by top.
char * toLowerCase(char *string)
Passes every UpperCase character from string to LowerCase.
string The string to be lowercased. A pointer to the lowercased string on success, NULL on error.
int isAllNumb(char *value)
Checks wether the given string contains only numbers.
value The string to be parsed. True if it's all numbers, False if not.