sysMalloc.c
static void* baseMalloc(size_t nbytes, memArea_t *memArea)
void sysFree(void *ap, memArea_t *(*getMemoryArea)())
Leaves avaiable the segment to be used in futures calls to sysMalloc. The memory segment is taken from the function pased by arguments.
ap The logical memory segment to be freed. getMemoryArea Function that returns the memory frame that sysMalloc wold be used in the future. sysRealloc() sysMalloc()
Referenced by free, kFree.
void* sysRealloc(void *ptr, size_t size, memArea_t *(*getMemoryArea)())
This function changes the original size of the logical memory to a new one if it's necesary.Returns null if theres not enough free space.
ptr Old logical memory segment, that could be moved to a new one. size The new size of the continuous memory segment. getMemoryArea Function that gives the frame to use be used by sysMalloc. The new continuous memory segment. sysFree() sysMalloc()
References memcpy, NULL, sysMalloc.
Referenced by kRealloc, realloc.
void* sysMalloc(size_t nbytes, memArea_t *(*getMemoryArea)())
Function that gives a continuous segment of memory. This memory comes from the function getMemoryArea. It could return null if there is not enougth free space on that frame.
nbytes the size of continuous segment memory. getMemoryArea Functions that gives the frame to use be used by sysMalloc. The continuous segment of memory. sysFree() sysRealloc()
Referenced by kMalloc, malloc, sysRealloc.