ttys.c
typedef void(* videoParser)(void))(void)
typedef void(* printFunctions)(int, tty_t))(int, tty_t)
unsigned char videoBuffer[VIDEO_MEMORY_SIZE][VIDEO_MEMORY_SIZE]
Referenced by fillScreen, printBackspace, printColorChar, printTab, putCharAtCurrentPos, putCharAtFixedPos, putColoredStringAtFixedPos, refreshScreen, updateColor.
process_t processTable[MAX_PROCESS][MAX_PROCESS]
process_t* runningProcess
process_t* initProcess
Keycode* keyboardBuffer
Referenced by charDeque, charEnque.
sysTTY ttyTable
tty_s TTYsList[MAX_TTY][MAX_TTY]
stdInTTY TTYstdIns[MAX_TTY][MAX_TTY]
stdOutTTY TTYstdOuts[MAX_TTY][MAX_TTY]
Keycode stdInBuffers[MAX_TTY][MAX_LINE][MAX_TTY][MAX_LINE]
Keycode stdOutBuffers[MAX_TTY][SCREEN_SIZE][MAX_TTY][SCREEN_SIZE]
unsigned int kbOffset[MAX_TTY][MAX_TTY]
videoParser videoParserFunctions[][]
void initializeTTY(void)
Create the table of ttys. The maximum of ttys is a define.
Use: ... initializeTTY(); ...
References CURSOR_START_COL, CURSOR_START_ROW, tty_s::focusProcess, sysTTY::focusTTY, tty_s::hasScrolled, sysTTY::listTTY, MAX_TTY, sysTTY::qtyTTY, tty_s::readCol, tty_s::readPointer, tty_s::readRow, STD_TTY, tty_s::stdIn, stdInTTY::stdInBuffer, tty_s::stdOut, stdOutTTY::stdOutBuffer, tty_s::ttyId, tty_s::writeCol, stdInTTY::writeOffset, tty_s::writePointer, tty_s::writeRow.
Referenced by kernel_main.
void getReadPointer(tty_t tty, int *readPointer, int *readCol, int *readRow)
This function obtains read pointers of the tty.
tty The tty where the function obtain the pointers readPointer The position of the pointer where it is reading readCol The col position of the stdout where it is reading readRow The row position of the stdout where it is reading
References sysTTY::listTTY, tty_s::readCol, tty_s::readPointer, tty_s::readRow.
void getWritePointer(tty_t tty, int *writePointer, int *writeCol, int *writeRow)
This function obtains writer pointers of the tty.
tty The tty where the function obtain the pointers writePointer The position of the pointer where it is writting writeCol The col position of the stdout where it is writting writeRow The row position of the stdout where it is writting
References sysTTY::listTTY, tty_s::writeCol, tty_s::writePointer, tty_s::writeRow.
void setReadPointer(tty_t tty, int readPointer, int readCol, int readRow)
This function saves the reads pointers of the tty that is indicated in the signature. This function is called when change the tty that is in focus, so it has to backup it's pointer.
tty The tty where the function save the pointers readPointer The position of the pointer where it is reading readCol The col position of the stdout where it is reading readRow The row position of the stdout where it is reading
References sysTTY::listTTY, tty_s::readCol, tty_s::readPointer, tty_s::readRow.
void setWritePointer(tty_t tty, int writePointer, int writeCol, int writeRow)
This function saves the reads pointers of the tty that is indicated in the signature. This function is called when change the tty who is in focus, so it has to backup his pointer.
tty The tty where the function save the pointers writePointer The position of the pointer where it is writting writeCol The col position of the stdout where it is writting writeRow The row position of the stdout where it is writting
References sysTTY::listTTY, tty_s::writeCol, tty_s::writePointer, tty_s::writeRow.
static void incReadPointer(int *readPointer, int *readCol, int *readRow)
static void decReadPointer(int *readPointer, int *readCol, int *readRow)
static void incWritePointer(int *writePointer, int *writeCol, int *writeRow)
static void decWritePointer(int *writePointer, int *writeCol, int *writeRow)
static FILE* sysGetTTYFocusedProcessStream(tty_t tty, int fd)
static void putLine(void)
static void parseAlarmTTY(int where, tty_t tty)
static void parseBackSpaceTTY(int where, tty_t tty)
static void parseTabTTY(int where, tty_t tty)
static void parseNewLineTTY(int where, tty_t tty)
static void parseVTabTTY(int where, tty_t tty)
static void parseLineFeedTTY(int where, tty_t tty)
static void parseReturnTTY(int where, tty_t tty)
static int parseCharTTY(int c, tty_t tty, int inStdIn)
static void refreshScreenTTY(void)
void putsTTY(unsigned char *name, int count, tty_t tty)
This function prints a string in a specific tty. It checks if it has to print only in the tty or in stdin too. It called to putCharTTy while the length of the string was grater than 0.
name The string to print count The size of the string tty The tty id where has to be printed the string Use: char*string="test"; ... putsTTY(string); ... putCharTTY
References putCharTTY, TRUE.
void putCharTTY(char c, tty_t tty, int inStdIn)
It prints only one character in specific tty. It verifies if the character is a control key or it belongs to the ASCII table. It checks if the tty is what are in focus, so it has to put the character in stdin buffer.
c The chacter to be printed tty The tty id where has to be printed inStdIn If it has to print in Stdin or not Use: char*string="System"; while(*string!=NULL) putCharTTY(*string++,tty,(TRUEvFALSE)):
References tty_s::hasScrolled, sysTTY::listTTY, SCREEN_SIZE, tty_s::writePointer.
Referenced by putsTTY, putTTYCharAtPosition, refreshKeyboardBufferTTY, refreshStdout.
int getFocusedTTY(void)
This function returns the tty id of tty that are in focus at this moment. It is a system called.
The id of tty that is in focus Use: inttty; tty=getFocusedTTY(); putCharTTY('a',tty,TRUE); ...
References sysTTY::focusTTY.
Referenced by changeFocusTTY, clearTTYScreen, handleException, putTTYCharAtPosition, refreshKeyboardBufferTTY, setTTYCursorPosition.
static void putTTY(Keycode c)
void refreshKeyboardBufferTTY(void)
Leaves all of character that are in the KeyboradBuffer and put in the correct tty stdout if the tty mode is CANONICAL, if not it prints directly in the STDIN of tty who is in focus. The timet tick is the responsible to call this function.
Use: ... callScheculer callrefreshKeyboardBufferTTY ... f1() f2()
References changeFocusTTY, charDeque, tty_s::focusProcess, sysTTY::focusTTY, getFocusedTTY, getProcessTable, getVideoColor, kbBufferIsEmpty, kill, sysTTY::listTTY, putCharTTY, TRUE, TTY_CANONICAL, process_t::ttyMode.
Referenced by keyboard_driver.
int changeFocusTTY(tty_t nextTty)
This function changes the tty focus id on the next Tty that has to be in focus. This function is called when the key that was pressed is between "F1" and "F7". Of every "F" key that was pressed, is put a value between 0x81 and 0x87. The number of the "F" key + 0x80.
nextTty Next tty id 1 if the next tty id is the current tty id in focus, 0 if it has changed the focus. Use: unsignedintc; while(!isEmptyKBBuffer()){ c=deQueue(); ... if(c>=0x81&&c<=0x87) changeFocusTTY(c-0x81);
References clearScreen, sysTTY::focusTTY, getFocusedTTY, sysTTY::listTTY, refreshScreen, setCursorPosition, tty_s::ttyId.
Referenced by refreshKeyboardBufferTTY.
void refreshStdout(void)
Pust all of character that are in the STDOUT and and puts in the tty STDOUT who is in focus.
Use:
References FALSE, putCharTTY, read, STDOUT, process_t::tty.
Referenced by battleship, refreshTTY.
void refreshTTY(void)
This functions check if the proccess if different of init and the running process has a valid pid, it only refreshes the stdout.
References NULL, process_t::pid, refreshScreen, refreshStdout, process_t::tty.
Referenced by handleException.
void sysSetTTYFocusedProcess(pid_t pid, tty_t tty)
Sets the pid to the process which is in focus.
pid The pid of the process tty The tty where will be set the pid of the process
References tty_s::focusProcess, sysTTY::listTTY.
Referenced by _sys_create_process, multitasker, terminate.
pid_t sysGetTTYFocusedProcess(tty_t tty)
Returns the pid of the process that is in this tty.
tty The tty where it is saved the pid of the focus process
References tty_s::focusProcess, sysTTY::listTTY.
void clearTTYScreen()
It clears the stdout of the tty that is in focus.
References clearScreen, getFocusedTTY, sysTTY::listTTY, MAX_TTY, SCREEN_SIZE, setCursorPosition, setTTYCursorPosition, tty_s::stdOut, stdOutTTY::stdOutBuffer, process_t::tty.
Referenced by goodbye, top, welcome.
void setTTYCursorPosition(int x, int y)
It sets the cursor in an specific position of the tty stdout.
x The row of the stdout y The column of the stdout
References getFocusedTTY, sysTTY::listTTY, MAX_TTY, SCREEN_HEIGTH, SCREEN_WIDTH, setCursorPosition, process_t::tty, tty_s::writeCol, tty_s::writePointer, tty_s::writeRow.
Referenced by clearTTYScreen, putTTYCharAtPosition, top.
void putTTYCharAtPosition(int c, int row, int col)
It puts a character in a specific position of the tty stdout. It prints the character at the position but it keeps the previous position.
c The character to be printed row The row where has to be printed col The column where has to be printed
References FALSE, getFocusedTTY, getVideoColor, sysTTY::listTTY, MAX_TTY, putCharAtCurrentPos, putCharTTY, refreshScreen, SCREEN_HEIGTH, SCREEN_WIDTH, setTTYCursorPosition, process_t::tty, tty_s::writeCol, tty_s::writePointer, tty_s::writeRow.